version: '3.8'

services:
  backend:
    build: .
    container_name: test2
    env_file:
      - .env
    ports:
      - "80:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    command: ["npm", "run", "start:dev"]

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
